### ISSUE TITLE
TypeError: Class constructor EcoPlugin cannot be invoked without 'new'

### ISSUE THREAD

**Issue by BrandonKlotz** [docpad/docpad-plugin-eco#12]
Seems like I am running into a similar issue as: https://github.com/docpad/docpad/issues/1089

Tried versions `docpad@6.7...docpad@6.8`

Current callstack from `docpad@6.79.4`

```
TypeError: Class constructor EcoPlugin cannot be invoked without 'new'
    at PluginLoader.load (/.../docs/node_modules/docpad/out/lib/plugin-loader.js:264:50)
    at /.../docs/node_modules/docpad/out/lib/docpad.js:4304:25
    at PluginLoader.unsupported (/.../docs/node_modules/docpad/out/lib/plugin-loader.js:207:5)
    at /.../docs/node_modules/docpad/out/lib/docpad.js:4288:23
    at success (/.../docs/node_modules/docpad/out/lib/plugin-loader.js:148:14)
    at /.../docs/node_modules/docpad/out/lib/plugin-loader.js:181:18
    at /.../docs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```

Possible solution, run `boundation`
- https://github.com/docpad/docpad/issues/1089#issuecomment-418095485

**Comment by balupton** [comment]
The eco plugin version you are using is not compatible with that version of docpad. Use version 6.80 or higher.
